In [1]:
N = ord("S") % 15 + 1
print(N)

9


In [2]:
import numpy as np
import random 
import copy
import time

##### assignment 1

In [3]:
# Exercise 1. Enter the number n. Output an array of size nхn, in which the diagonals
# are numbers from 1 to n, and other elements are 0

In [7]:
n = int(input("enter a number"))
# using numpy universal functions
start_time = time.time()
arr = np.eye(n) * np.arange(1, n + 1) 
end_time = time.time()
print("Read_Time_taken_using numpy: " + str(end_time - start_time)+" sec")
print(arr)

# using using iterative constructions (using loops, list comprehensions, etc.).
print("\n")
start_time = time.time()
arr1 = np.zeros((n,n))
for i in range(n):
    arr1[i, i] = i+1
end_time = time.time()
print("Read_Time_taken_using iterative constructions: " + str(end_time - start_time)+" sec")
print(arr1)

enter a number3
Read_Time_taken_using numpy: 0.0 sec
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


Read_Time_taken_using iterative constructions: 0.0010001659393310547 sec
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [6]:
# Exercise 2. Enter the number n. Arrange 1 and 0 in a checkerboard pattern, starting
#  with 0 in a matrix of size nхn, using slicing.

In [3]:
val1 = int(input("Enter the value of: \n"))
# using numpy universal functions

arr = np.ones((val1, val1), dtype=int)
start_time = time.time()
arr[::2, ::2] = 0
arr[1::2, 1::2] = 0
end_time = time.time()
print("Read_Time_taken_using numpy: " + str(end_time - start_time)+" sec")
print(arr)
print("\n")
# using using iterative constructions (using loops, list comprehensions, etc.).
arr1 = np.ones((val1, val1), dtype=int)
start_time = time.time()
rows = []
for i in range(val1):
    row = []
   
    for j in range(val1):
        if (i+j) % 2 == 0:
            row.append(0)
        else:
            row.append(1)
    rows.append(row)

arr1 = np.array(rows)
end_time = time.time()
print("Read_Time_taken_using iterative constructions: " + str(end_time - start_time)+" sec")
print(arr)

Enter the value of: 
3
Read_Time_taken_using numpy: 0.0 sec
[[0 1 0]
 [1 0 1]
 [0 1 0]]


Read_Time_taken_using iterative constructions: 0.03841352462768555 sec
[[0 1 0]
 [1 0 1]
 [0 1 0]]


In [8]:
# Exercise 4. Enter the numbers n and m. Output an array of size nхm, in which the
# first line (line with zero index) are numbers from 0 to m-1, and all other elements
# of the matrix are equal to 0.

In [12]:
n = int(input("Enter the value of n: \n"))
m = int(input("Enter the value of m: \n"))

# using numpy universal functions
arr = np.zeros((n, m), dtype=int)
start_time = time.time()
arr[0] = np.arange(m)
end_time = time.time()
print("Read_Time_taken_using numpy: " + str(end_time - start_time)+" sec")
print(arr)

print("\n")
# using using iterative constructions (using loops, list comprehensions, etc.).

arr1 = arr1 = np.zeros((n, m), dtype=int)
start_time = time.time()
for j in range(m):
    arr1[0][j] = j

end_time = time.time()
print("Read_Time_taken_using iterative constructions: " + str(end_time - start_time)+" sec")
print(arr1)



Enter the value of n: 
2
Enter the value of m: 
3
Read_Time_taken_using numpy: 0.0 sec
[[0 1 2]
 [0 0 0]]


Read_Time_taken_using iterative constructions: 0.0 sec
[[0 1 2]
 [0 0 0]]


In [5]:
# Exercise 7. An array is entered from the keyboard. Replace all zeros with -1.

In [16]:
a = int(input("enter number of elements\n"))
print("enter numbers")

# using numpy universal functions
arr = np.array(list(map(int, input("Enter the array: ").split())))
start_time = time.time()
arr[arr == 0] = -1
end_time = time.time()
print("Read_Time_taken_using numpy: " + str(end_time - start_time)+" sec")
print(arr)
print("\n")
# using using iterative constructions (using loops, list comprehensions, etc.).
arr1 = np.array(list(map(int, input("Enter the array: ").split())))
start_time = time.time()
for i in range(a):
    if arr1[i] == 0:
        arr1[i] = -1
end_time = time.time()
print("Read_Time_taken_using iterative constructions: " + str(end_time - start_time)+" sec")
print(arr1)

enter number of elements
4
enter numbers
Enter the array: 0 0 0 0
Read_Time_taken_using numpy: 0.0 sec
[-1 -1 -1 -1]


Enter the array: 0 0 0 0
Read_Time_taken_using iterative constructions: 0.0 sec
[-1 -1 -1 -1]


In [ ]:
# Exercise 8. An array is entered from the keyboard. Count the number of zero and
# non-zero elements in it.

In [17]:
# Exercise 8. An array is entered from the keyboard. Count the number of zero and
a = int(input("enter number of elements\n"))
arr = np.array(list(map(int, input("Enter the array: ").split())))
start_time = time.time()
num_zero = np.count_nonzero(arr == 0)

num_nonzero = np.count_nonzero(arr != 0)

print("Zeros:", num_zero)
print("Non-zeros:", num_nonzero)
end_time = time.time()
print("Read_Time_taken_using numpy: " + str(end_time - start_time)+" sec")
print("\n")
# using using iterative constructions (using loops, list comprehensions, etc.).

arr1 = np.array(list(map(int, input("Enter the array: ").split())))
x, y = 0, 0
start_time = time.time()
for i in range(a):
    if arr1[i] == 0:
        x += 1
    else:
        y +=1
        
print("Zeros:", x)
print("Non-zeros:", y)
end_time = time.time()
print("Read_Time_taken_using iterative constructions: " + str(end_time - start_time)+" sec")

enter number of elements
4
Enter the array: 1 2 0 3
Zeros: 1
Non-zeros: 3
Read_Time_taken_using numpy: 0.0 sec


Enter the array: 4 2 0 0
Zeros: 2
Non-zeros: 2
Read_Time_taken_using iterative constructions: 0.0 sec


In [1]:
# Exercise 12. Create an array of 1 of size nхn and create an inside "border" formed
# from 0.

In [20]:
# using numpy universal functions
n = int(input("Enter the size of the array: "))
arr = np.zeros((n, n), dtype=int)
start_time = time.time()
arr[1:-1, 1:-1] = 1
end_time = time.time()
print("Read_Time_taken_using numpy: " + str(end_time - start_time)+" sec")
print(arr)
print("\n")
# using using iterative constructions (using loops, list comprehensions, etc.).
arr1 = np.zeros((n, n), dtype=int)
start_time = time.time()
for i in range(1, n-1):
    for j in range(1, n-1):
        arr1[i][j] = 1
end_time = time.time()
print("Read_Time_taken_using iterative constructions: " + str(end_time - start_time)+" sec")
print(arr1)

Enter the size of the array: 4
Read_Time_taken_using numpy: 0.0 sec
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


Read_Time_taken_using iterative constructions: 0.0010197162628173828 sec
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


In [6]:
# Exercise 15. Fill the even columns of the matrix of nхn size with 1, and the odd
# ones with 0

In [29]:
# using numpy universal functions
n = int(input("Enter the size of the array: "))
arr = np.ones((n,n))
start_time = time.time()
arr[: , ::2] = 0
end_time = time.time()
print("Read_Time_taken_using numpy: " + str(end_time - start_time)+" sec")
print(arr)
print("\n")
# using using iterative constructions (using loops, list comprehensions, etc.).
arr1 = np.ones((n,n))
start_time = time.time()
for i in range(n):
    for j in range(n):
        if not j % 2 == 0:
            arr1[i][j] = 1
        else:
            arr1[i][j] = 0

end_time = time.time()
print("Read_Time_taken_using iterative constructions: " + str(end_time - start_time)+" sec")
print(arr1)

Enter the size of the array: 4
Read_Time_taken_using numpy: 0.0 sec
[[0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]]


Read_Time_taken_using iterative constructions: 0.0 sec
[[0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]]


In [24]:
# Exercise 16. Fill the vector with values from 0 to n. Replace all values greater than
# n/2 and less than 3n/4 with zeros.

In [33]:
# using numpy universal functions
n = int(input("Enter the size of the array: "))
start_time = time.time()
arr = np.arange(n + 1)
arr[(arr >= n / 2) & (arr < (3 * n) / 4)] = 0
end_time = time.time()
print("Read_Time_taken_using numpy: " + str(end_time - start_time)+" sec")
print(arr)
print("\n")
# using using iterative constructions (using loops, list comprehensions, etc.).
arr1 = np.arange(n + 1)
start_time = time.time()
for i in range(n):
    if arr1[i] >= n / 2 and arr1[i] < 3 * n / 4:
        arr1[i] = 0

end_time = time.time()
print("Read_Time_taken_using iterative constructions: " + str(end_time - start_time)+" sec")
print(arr1)

Enter the size of the array: 10
Read_Time_taken_using numpy: 0.0 sec
[ 0  1  2  3  4  0  0  0  8  9 10]


Read_Time_taken_using iterative constructions: 0.0 sec
[ 0  1  2  3  4  0  0  0  8  9 10]


In [10]:
# Exercise 20. Generate a vector of n random elements, lying in the interval (0,1).
# Replace the maximum element with 0. 

In [40]:
# using numpy universal functions
n = int(input("Enter the size of the array: "))
start_time = time.time()
arr = np.random.rand(n)
max_val = np.argmax(arr)
print(f"the array before {arr}")
arr[max_val] = 0
print(f"the array after {arr}")
end_time = time.time()
print("Read_Time_taken_using numpy: " + str(end_time - start_time)+" sec")
print("\n")

# using using iterative constructions (using loops, list comprehensions, etc.).
start_time = time.time()
arr1 = np.random.rand(n)
print(f"the array before {arr1}")
max_index = 0
max_val1 = 0
for i in range(n):
    if arr1[i] > max_val1:
        max_val1 = arr1[i]
        max_index = i
arr1[max_index] = 0
print(f"the array after {arr1}")
end_time = time.time()
print("Read_Time_taken_using iterative constructions: " + str(end_time - start_time)+" sec")

Enter the size of the array: 5
the array before [0.69411427 0.44883957 0.50923974 0.37359561 0.60132491]
the array after [0.         0.44883957 0.50923974 0.37359561 0.60132491]
Read_Time_taken_using numpy: 0.0 sec


the array before [0.37206683 0.4033589  0.7029644  0.59619528 0.83293565]
the array after [0.37206683 0.4033589  0.7029644  0.59619528 0.        ]
Read_Time_taken_using iterative constructions: 0.0 sec


In [38]:
# 2. Solve the system of linear equations using Cramer's formulas and check the 
# result using:
# a) matrix multiplication;
# b) inverse matrix;
# c) numpy.linalg.solve().
# Compare the results using numpy.allclose().

In [22]:
a = np.array([[1, 2, 1, 1], 
              [2, 1, 1, 1], 
              [1, -1, 2, 1], 
              [1, 1, -1, 3]])

b = np.array([8, 5, -1, 10])
# Solving the equation using cramer rule
detA = np.linalg.det(a)

mat1 = copy.deepcopy(a)
mat1[:, 0] = b

mat2 = copy.deepcopy(a)
mat2[:, 1] = b

mat3 = copy.deepcopy(a)
mat3[:, 2] = b

mat4 = copy.deepcopy(a)
mat4[:, 3] = b

detX1 = np.linalg.det(mat1)
detX2 = np.linalg.det(mat2)
detX3 = np.linalg.det(mat3)
detX4 = np.linalg.det(mat4)

x1 = detX1 / detA
x2 = detX2 / detA
x3 = detX3 / detA
x4 = detX4 / detA
#  RESULT
x = np.array([x1, x2, x3, x4])

# a) matrix multiplication;
result = np.dot(a, x)
print(f"The result compared to the result of using matrix multiplication is {np.allclose(result, b)}\n")

# b) inverse matrix
inv_matrix = np.linalg.inv(a)
result1 = np.dot(inv_matrix, b)
print(f"The result compared to the result of using inverse matrix is {np.allclose(result1, x)}\n")
# c) numpy.linalg.solve().
result2 = np.linalg.solve(a, b)
print(f"The result compared to the result of using numpy.linalg.solve() is {np.allclose(result2, x)}\n")


The result compared to the result of using matrix multiplication is True

The result compared to the result of using inverse matrix is True

The result compared to the result of using numpy.linalg.solve() is True



In [2]:
# 3. Calculate the value of the matrix expression
# a) using the universal functions of the NumPy library.
# b) using iterative constructions (using loops, list comprehensions, etc.).
# c) for both cases, calculate the execution time of the script and compare the
# values.
# Compare the results using numpy.allclose().

##### we use this formula for matrix multiplication

$$\mathbf {(AB)}_{ij} = \sum_{k = 1}^n A_{ik} B_{kj}$$

In [7]:
# a) using the universal functions of the NumPy library.
a = np.array([[1, 4, 2], [2, 1, -2], [0, 1, -1]])
b = np.array([[4, 6, -2], [4, 10, 1], [2, 4, -5]])

start_time = time.time()
result = 2 * a - (a @ a + b) @ b
end_time = time.time()
print(result)
print("Read_Time_taken_using numpy: " + str(end_time - start_time) + " sec")

# b) using iterative constructions (using loops, list comprehensions, etc.).
c = np.array([[1, 4, 2], [2, 1, -2], [0, 1, -1]])
d = np.array([[4, 6, -2], [4, 10, 1], [2, 4, -5]])

start_time = time.time()

doubleC = copy.deepcopy(c)
for i in range(len(doubleC)):
    for j in range(len(doubleC[i])):
        doubleC[i][j] = doubleC[i][j] * 2

powerC = np.zeros((3, 3))
for i in range(len(powerC)):
    for j in range(len(powerC[0])):
        for k in range(len(powerC)):
            powerC[i][j] += c[i][k] * c[k][j]

powerCPlusD = np.zeros((3, 3))
for i in range(len(powerC)):
    for j in range(len(powerC[i])):
        powerCPlusD[i][j] = powerC[i][j] + d[i][j]

powerCPlusDTimesD = np.zeros((3, 3))

for i in range(len(powerC)):
    for j in range(len(powerC[0])):
        for k in range(len(powerC)):
            powerCPlusDTimesD[i][j] += powerCPlusD[i][k] * d[k][j]

result2 = np.zeros((3, 3))
for i in range(len(powerC)):
    for j in range(len(powerC[i])):
        result2[i][j] = doubleC[i][j] - powerCPlusDTimesD[i][j]

end_time = time.time()
print(result2)
print("Read_Time_taken_using iterative constructions: " + str(end_time - start_time) + " sec")
print(f"The Results comparison of using numpy and iterative constructions is {np.allclose(result, result2)}")


[[ -94 -190  -36]
 [-106 -236   20]
 [ -20  -38  -28]]
Read_Time_taken_using numpy: 0.0009999275207519531 sec
[[ -94. -190.  -36.]
 [-106. -236.   20.]
 [ -20.  -38.  -28.]]
Read_Time_taken_using iterative constructions: 0.003000974655151367 sec
The Results comparison of using numpy and iterative constructions is True
